# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'A propos', path: 'menu', url: 'about.html'}
- {name: 'Articles', path: 'menu', url: 'writing.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:chloe.allemann@hotmail.com'}


# Customize site text
pagination:
  next_page: 'Plus récent'
  previous_page: 'Plus vieux'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Pourrait aussi vous intéresser:'

post_date_prefix: 'Ecrit le'
